import type { CSSProperties } from 'react';

const bg = '#1C1C1E';
const fg = '#FFFFFF';
const fgMuted = '#A1A1AA';
const accent = '#3B82F6';

export const styles: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    background: bg,
    color: fg,
    padding: '2rem 1rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  hero: {
    textAlign: 'center',
    maxWidth: 600,
    marginBottom: '2.5rem',
  },
  title: {
    fontSize: 42,
    fontWeight: 800,
    color: fg,
    margin: '0 0 0.75rem',
    lineHeight: 1.1,
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: 20,
    color: fgMuted,
    margin: 0,
    lineHeight: 1.5,
  },
  searchBox: {
    width: '100%',
    maxWidth: 520,
    background: '#2C2C2E',
    borderRadius: 20,
    padding: '1.75rem',
    marginBottom: '1.5rem',
    overflow: 'hidden',
  },
  inputRow: {
    display: 'flex',
    gap: '0.75rem',
    alignItems: 'stretch',
  },
  input: {
    flex: 1,
    minWidth: 0,
    fontSize: 22,
    padding: '0.75rem 1.25rem',
    borderRadius: 14,
    border: '2px solid #3A3A3C',
    background: '#1C1C1E',
    color: fg,
    outline: 'none',
    minHeight: 56,
  },
  searchBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 56,
    minWidth: 56,
    borderRadius: 14,
    border: 'none',
    background: accent,
    color: '#fff',
    cursor: 'pointer',
    minHeight: 56,
    flexShrink: 0,
  },
  separator: {
    textAlign: 'center',
    fontSize: 16,
    color: fgMuted,
    padding: '0.75rem 0',
  },
  voiceBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    width: '100%',
    padding: '0.9rem',
    borderRadius: 14,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: '#3A3A3C',
    background: '#1C1C1E',
    color: '#34D399',
    fontSize: 20,
    fontWeight: 600,
    cursor: 'pointer',
    minHeight: 56,
  },
  voiceLabel: {
    fontSize: 20,
  },
  hint: {
    fontSize: 16,
    color: fgMuted,
    textAlign: 'center',
    margin: '0.75rem 0 0',
  },
  infoCards: {
    width: '100%',
    maxWidth: 520,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  infoCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem 1.25rem',
    background: '#2C2C2E',
    borderRadius: 14,
  },
  infoCardEmoji: {
    fontSize: 28,
    flexShrink: 0,
  },
  infoCardText: {
    fontSize: 18,
    color: fg,
    lineHeight: 1.4,
  },
  infoCardSub: {
    display: 'block',
    fontSize: 16,
    color: fgMuted,
    marginTop: '0.15rem',
  },

  resultsContainer: {
    minHeight: '100vh',
    background: bg,
    color: fg,
    padding: '1rem',
  },
  resultsHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '1rem',
    paddingBottom: '0.75rem',
    borderBottom: '1px solid #3A3A3C',
  },
  backBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 48,
    height: 48,
    borderRadius: 12,
    border: '2px solid #3A3A3C',
    background: '#2C2C2E',
    color: fg,
    cursor: 'pointer',
    fontSize: 22,
    flexShrink: 0,
  },
  resultsTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: fg,
    margin: 0,
    flex: 1,
  },
  resultsCount: {
    fontSize: 16,
    color: fgMuted,
  },
  resultCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem 1.25rem',
    background: '#2C2C2E',
    borderRadius: 14,
    marginBottom: '0.75rem',
    cursor: 'pointer',
    minHeight: 80,
  },
  resultImg: {
    width: 56,
    height: 56,
    borderRadius: 10,
    objectFit: 'contain' as const,
    background: '#1C1C1E',
    flexShrink: 0,
  },
  resultImgPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 10,
    background: '#3A3A3C',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 24,
    flexShrink: 0,
  },
  resultInfo: {
    flex: 1,
    minWidth: 0,
  },
  resultName: {
    fontSize: 19,
    fontWeight: 700,
    color: fg,
    lineHeight: 1.3,
    marginBottom: '0.25rem',
  },
  resultLaboratorio: {
    fontSize: 16,
    color: fgMuted,
    marginBottom: '0.25rem',
  },
  badgeRow: {
    display: 'flex',
    gap: '0.35rem',
    flexWrap: 'wrap',
  },
  badgeBase: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    padding: '0.2rem 0.5rem',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 700,
    lineHeight: '1.4',
  },
  badgeRecetaRoja: {
    background: 'rgba(211,47,47,0.2)',
    color: '#EF5350',
  },
  badgeRecetaVerde: {
    background: 'rgba(76,175,80,0.2)',
    color: '#66BB6A',
  },
  badgeConduc: {
    background: 'rgba(245,124,0,0.2)',
    color: '#FFA726',
  },
  badgeGenerico: {
    background: 'rgba(59,130,246,0.2)',
    color: '#60A5FA',
  },
  badgeTriangulo: {
    background: 'rgba(168,85,247,0.2)',
    color: '#C084FC',
  },
  badgePsico: {
    background: 'rgba(239,68,68,0.2)',
    color: '#F87171',
  },
  badgeHospital: {
    background: 'rgba(6,182,212,0.2)',
    color: '#22D3EE',
  },
  badgePsum: {
    background: 'rgba(236,72,153,0.2)',
    color: '#F472B6',
  },
  badgeNoComerc: {
    background: 'rgba(161,161,170,0.2)',
    color: '#A1A1AA',
  },
  noResults: {
    textAlign: 'center',
    padding: '3rem 1rem',
    color: fgMuted,
    fontSize: 20,
  },
  loader: {
    textAlign: 'center',
    padding: '3rem 1rem',
    color: accent,
    fontSize: 18,
  },

  // Detail redesign — compacto, horizontal alerts, grid info
  detailContainer: {
    minHeight: '100vh',
    background: bg,
    color: fg,
    padding: '1rem',
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.75rem',
    marginBottom: '0.75rem',
  },
  detailBody: {
    maxWidth: 560,
    margin: '0 auto',
  },
  detailImg: {
    width: '100%',
    maxWidth: 200,
    height: 'auto',
    aspectRatio: '1',
    borderRadius: 16,
    objectFit: 'contain' as const,
    background: '#2C2C2E',
  },
  detailName: {
    fontSize: 22,
    fontWeight: 800,
    color: fg,
    lineHeight: 1.25,
    marginBottom: '0.2rem',
  },
  detailByline: {
    fontSize: 15,
    color: fgMuted,
    lineHeight: 1.4,
  },

  // Alert chips row (horizontal wrapping)
  alertChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
    padding: '0.45rem 0.9rem',
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 700,
    lineHeight: '1.4',
    whiteSpace: 'nowrap' as const,
  },
  chipTooltipWrap: {
    position: 'relative' as const,
    display: 'inline-flex',
  },
  chipTooltip: {
    position: 'absolute' as const,
    bottom: 'calc(100% + 8px)',
    left: '50%',
    transform: 'translateX(-50%) translateY(4px)',
    background: '#3A3A3C',
    color: '#E4E4E7',
    padding: '0.45rem 0.75rem',
    borderRadius: 8,
    fontSize: 12,
    lineHeight: 1.3,
    fontWeight: 500,
    whiteSpace: 'nowrap' as const,
    opacity: 0,
    visibility: 'hidden',
    transition: 'opacity 0.15s ease, transform 0.15s ease, visibility 0.15s',
    pointerEvents: 'none' as const,
    zIndex: 20,
    maxWidth: 260,
  },
  chipTooltipArrow: {
    position: 'absolute' as const,
    top: '100%',
    left: '50%',
    transform: 'translateX(-50%)',
    width: 0,
    height: 0,
    borderLeft: '5px solid transparent',
    borderRight: '5px solid transparent',
    borderTop: '5px solid #3A3A3C',
  },


  chipReceta: {
    background: 'rgba(211,47,47,0.18)',
    color: '#EF5350',
    border: '1px solid rgba(211,47,47,0.3)',
  },
  chipNoReceta: {
    background: 'rgba(76,175,80,0.18)',
    color: '#66BB6A',
    border: '1px solid rgba(76,175,80,0.3)',
  },
  chipConduc: {
    background: 'rgba(245,124,0,0.18)',
    color: '#FFA726',
    border: '1px solid rgba(245,124,0,0.3)',
  },
  chipTriangulo: {
    background: 'rgba(168,85,247,0.18)',
    color: '#C084FC',
    border: '1px solid rgba(168,85,247,0.3)',
  },
  chipPsico: {
    background: 'rgba(239,68,68,0.18)',
    color: '#F87171',
    border: '1px solid rgba(239,68,68,0.3)',
  },
  chipHospital: {
    background: 'rgba(6,182,212,0.18)',
    color: '#22D3EE',
    border: '1px solid rgba(6,182,212,0.3)',
  },
  chipPsum: {
    background: 'rgba(236,72,153,0.18)',
    color: '#F472B6',
    border: '1px solid rgba(236,72,153,0.3)',
  },
  chipGenerico: {
    background: 'rgba(59,130,246,0.18)',
    color: '#60A5FA',
    border: '1px solid rgba(59,130,246,0.3)',
  },
  chipBiosimilar: {
    background: 'rgba(20,184,166,0.18)',
    color: '#34D399',
    border: '1px solid rgba(20,184,166,0.3)',
  },
  chipNoComerc: {
    background: 'rgba(161,161,170,0.18)',
    color: '#A1A1AA',
    border: '1px solid rgba(161,161,170,0.3)',
  },
  chipNotas: {
    background: 'rgba(234,179,8,0.18)',
    color: '#FBBF24',
    border: '1px solid rgba(234,179,8,0.3)',
  },

  // Summary info grid (2-column on wide enough screens)
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.5rem',
    marginBottom: '0.75rem',
  },
  infoGridItem: {
    background: '#2C2C2E',
    borderRadius: 12,
    padding: '0.65rem 0.85rem',
  },
  infoGridLabel: {
    fontSize: 11,
    color: fgMuted,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.3px',
    marginBottom: '0.15rem',
  },
  infoGridValue: {
    fontSize: 15,
    color: fg,
    fontWeight: 600,
    lineHeight: 1.3,
  },

  // Sections
  section: {
    marginBottom: '0.75rem',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '0.4rem',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: fg,
  },
  sectionToggle: {
    fontSize: 13,
    color: accent,
    fontWeight: 600,
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    fontFamily: 'inherit',
  },

  // Compact card for composición / ATC / presentaciones
  compactCard: {
    background: '#2C2C2E',
    borderRadius: 12,
    padding: '0.65rem 0.85rem',
  },
  princRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    marginBottom: '0.3rem',
  },
  princDot: {
    fontSize: 10,
    color: '#60A5FA',
    fontWeight: 700,
    flexShrink: 0,
  },
  princName: {
    fontSize: 15,
    color: fg,
    fontWeight: 600,
  },
  princDosis: {
    fontSize: 14,
    color: fgMuted,
  },

  chipAtc: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.3rem',
    padding: '0.2rem 0.5rem',
    borderRadius: 6,
    background: 'rgba(59,130,246,0.15)',
    color: '#60A5FA',
    fontSize: 12,
    fontWeight: 700,
    marginRight: '0.35rem',
    marginBottom: '0.25rem',
  },

  presRow: {
    padding: '0.5rem 0',
    borderBottom: '1px solid #3A3A3C',
  },
  presName: {
    fontSize: 14,
    color: fg,
    lineHeight: 1.3,
    marginBottom: '0.15rem',
  },
  presMeta: {
    display: 'flex',
    gap: '0.5rem',
    fontSize: 12,
    color: fgMuted,
  },
  presTag: {
    color: '#F87171',
    fontWeight: 600,
  },
  presTagPsum: {
    color: '#F472B6',
    fontWeight: 600,
  },

  // Actions row
  actionRow: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '0.75rem',
    flexWrap: 'wrap' as const,
  },
  actionBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.4rem',
    padding: '0.6rem 1rem',
    borderRadius: 10,
    border: 'none',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
    flex: 1,
    minHeight: 44,
    minWidth: 0,
  },
  actionPlay: {
    background: accent,
    color: '#fff',
  },
  actionStop: {
    background: '#3A3A3C',
    color: fg,
  },
  actionPdf: {
    background: '#2C2C2E',
    color: fg,
    border: '2px solid #3A3A3C',
    flex: 1,
  },

  // Legend button + dropdown
  legendBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: '50%',
    border: '1px solid #52525B',
    background: 'transparent',
    color: '#A1A1AA',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'background 0.15s, border-color 0.15s, color 0.15s',
  },
  legendDropdown: {
    position: 'absolute' as const,
    top: 'calc(100% + 6px)',
    right: 0,
    background: '#27272A',
    border: '1px solid #3F3F46',
    borderRadius: 12,
    padding: '0.5rem',
    minWidth: 220,
    zIndex: 30,
    boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
    padding: '0.4rem 0.5rem',
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.4,
    color: '#D4D4D8',
  },

  // Footer
  footerNote: {
    textAlign: 'center',
    padding: '1rem 0',
    fontSize: 12,
    color: '#6B7280',
    lineHeight: 1.5,
  },
};
