import type { CSSProperties } from 'react'

// Tokens visuales compartidos del panel administrativo (coherente con Nartalis dark theme)
export const A = {
  bg: '#1C1C1E',
  card: '#2C2C2E',
  cardBorder: 'rgba(255,255,255,0.07)',
  fg: '#FFFFFF',
  muted: '#A1A1AA',
  faint: '#71717A',
  accent: '#6748FD',
  accentSoft: 'rgba(103,72,253,0.18)',
  accentText: '#C4B5FD',
  green: '#66BB6A',
  greenSoft: 'rgba(76,175,80,0.15)',
  red: '#F87171',
  redSoft: 'rgba(239,68,68,0.15)',
  amber: '#FBBF24',
  amberSoft: 'rgba(251,191,36,0.12)',
  blue: '#60A5FA',
  blueSoft: 'rgba(59,130,246,0.15)',
  rowBorder: '#3A3A3C',
} as const

export const adminS: Record<string, CSSProperties> = {
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: '0.75rem',
    marginBottom: '1.5rem',
  },
  card: {
    background: A.card,
    border: `1px solid ${A.cardBorder}`,
    borderRadius: 14,
    padding: '1rem 1.1rem',
  },
  kpiLabel: {
    fontSize: 12,
    color: A.faint,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.4px',
    marginBottom: '0.3rem',
  },
  kpiValue: {
    fontSize: 26,
    fontWeight: 800,
    color: A.fg,
    letterSpacing: '-0.02em',
  },
  kpiSub: {
    fontSize: 12,
    color: A.muted,
    marginTop: '0.15rem',
  },
  section: {
    marginBottom: '1.5rem',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: A.fg,
    margin: '0 0 0.75rem',
  },
  tableWrap: {
    background: A.card,
    border: `1px solid ${A.cardBorder}`,
    borderRadius: 14,
    overflow: 'hidden' as const,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: 13,
  },
  th: {
    textAlign: 'left' as const,
    padding: '0.65rem 0.9rem',
    color: A.faint,
    fontWeight: 700,
    fontSize: 11,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.4px',
    borderBottom: `1px solid ${A.rowBorder}`,
    whiteSpace: 'nowrap' as const,
  },
  td: {
    padding: '0.65rem 0.9rem',
    color: A.fg,
    borderBottom: '1px solid rgba(58,58,60,0.5)',
    verticalAlign: 'middle' as const,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0.15rem 0.55rem',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  badgeGreen: { background: A.greenSoft, color: A.green },
  badgeRed: { background: A.redSoft, color: A.red },
  badgeAmber: { background: A.amberSoft, color: A.amber },
  badgeBlue: { background: A.blueSoft, color: A.blue },
  badgePurple: { background: A.accentSoft, color: A.accentText },
  badgeGray: { background: 'rgba(161,161,170,0.15)', color: A.muted },
  input: {
    width: '100%',
    padding: '0.5rem 0.75rem',
    borderRadius: 10,
    border: '1px solid #3A3A3C',
    background: '#1C1C1E',
    color: A.fg,
    fontSize: 14,
    fontFamily: 'inherit',
    outline: 'none',
  },
  select: {
    padding: '0.5rem 0.75rem',
    borderRadius: 10,
    border: '1px solid #3A3A3C',
    background: '#1C1C1E',
    color: A.fg,
    fontSize: 14,
    fontFamily: 'inherit',
  },
  toolbar: {
    display: 'flex',
    gap: '0.5rem',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    marginBottom: '1rem',
  },
  btn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.35rem',
    padding: '0.45rem 0.9rem',
    borderRadius: 10,
    border: 'none',
    background: A.accentSoft,
    color: A.accentText,
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'background 0.15s',
  },
  btnGhost: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.35rem',
    padding: '0.45rem 0.9rem',
    borderRadius: 10,
    border: '1px solid #3A3A3C',
    background: 'transparent',
    color: A.muted,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  empty: {
    padding: '2rem',
    textAlign: 'center' as const,
    color: A.muted,
    fontSize: 14,
  },
  error: {
    padding: '1rem',
    borderRadius: 12,
    background: A.redSoft,
    border: '1px solid rgba(239,68,68,0.3)',
    color: A.red,
    fontSize: 13,
    marginBottom: '1rem',
  },
}
