import type { CSSProperties } from 'react';

const bg = '#1C1C1E';
const fg = '#FFFFFF';
const fgMuted = '#A1A1AA';
const accent = '#3B82F6';

export const styles: Record<string, CSSProperties> = {
  pageWrap: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem 1rem',
  },
  card: {
    width: '100%',
    maxWidth: 440,
    background: bg,
    borderRadius: 20,
    padding: '2rem',
    border: '1px solid rgba(255,255,255,0.08)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.35)',
  },
  brand: {
    textAlign: 'center' as const,
    fontSize: 22,
    fontWeight: 800,
    color: fg,
    margin: '0 0 0.35rem',
    letterSpacing: '-0.02em',
  },
  title: {
    fontSize: 26,
    fontWeight: 800,
    color: fg,
    margin: '0 0 0.5rem',
    lineHeight: 1.25,
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: 15,
    color: fgMuted,
    margin: '0 0 1.5rem',
    lineHeight: 1.5,
  },
  providerBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    minHeight: 48,
    padding: '0.6rem 1rem',
    borderRadius: 12,
    background: '#2C2C2E',
    border: '1px solid #3A3A3C',
    color: fg,
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'background 0.15s, border-color 0.15s',
  },
  providerRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.7rem',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    margin: '1.25rem 0',
    color: fgMuted,
    fontSize: 14,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    background: 'rgba(255,255,255,0.08)',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
    marginBottom: '0.9rem',
  },
  label: {
    fontSize: 14,
    color: '#D4D4D8',
    fontWeight: 600,
  },
  input: {
    width: '100%',
    minHeight: 48,
    padding: '0.6rem 0.9rem',
    borderRadius: 12,
    border: '2px solid #3A3A3C',
    background: '#141416',
    color: fg,
    fontSize: 16,
    fontFamily: 'inherit',
    outline: 'none',
  },
  submitBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    width: '100%',
    minHeight: 48,
    padding: '0.6rem 1rem',
    borderRadius: 12,
    border: 'none',
    background: 'linear-gradient(135deg, #6748FD, #947FFF)',
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'inherit',
    marginTop: '0.25rem',
    transition: 'opacity 0.15s',
  },
  submitBtnDisabled: {
    opacity: 0.6,
    cursor: 'default',
  },
  error: {
    fontSize: 14,
    color: '#F87171',
    margin: '0.75rem 0 0',
    lineHeight: 1.4,
  },
  notice: {
    fontSize: 14,
    color: '#FBBF24',
    margin: '0.75rem 0 0',
    lineHeight: 1.4,
  },
  legal: {
    fontSize: 12,
    color: '#71717A',
    margin: '1rem 0 0',
    lineHeight: 1.5,
    textAlign: 'center' as const,
  },
  legalLink: {
    color: '#A1A1AA',
    textDecoration: 'underline',
  },
  switchRow: {
    marginTop: '1.25rem',
    textAlign: 'center' as const,
    fontSize: 14,
    color: fgMuted,
  },
  switchLink: {
    background: 'none',
    border: 'none',
    padding: 0,
    color: accent,
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: 14,
    fontWeight: 600,
  },
  forgotRow: {
    textAlign: 'right' as const,
    marginTop: '0.35rem',
  },
  forgotBtn: {
    background: 'none',
    border: 'none',
    padding: 0,
    color: fgMuted,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  spinner: {
    animation: 'farmaSpin 1s linear infinite',
  },

  // Pantalla de transición /espacio
  spaceWrap: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem 1rem',
    textAlign: 'center' as const,
  },
  spaceCard: {
    width: '100%',
    maxWidth: 480,
    background: bg,
    borderRadius: 20,
    padding: '2.5rem 2rem',
    border: '1px solid rgba(255,255,255,0.08)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.35)',
  },
  spaceIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    height: 64,
    borderRadius: '50%',
    background: 'linear-gradient(135deg, rgba(103,72,253,0.35), rgba(103,72,253,0.12))',
    border: '1px solid rgba(103,72,253,0.45)',
    margin: '0 auto 1.25rem',
  },
  spaceCheck: {
    fontSize: 30,
    fontWeight: 800,
    color: '#FFFFFF',
    lineHeight: 1,
  },
  spaceTitle: {
    fontSize: 24,
    fontWeight: 800,
    color: fg,
    margin: '0 0 0.75rem',
    lineHeight: 1.3,
  },
  spaceText: {
    fontSize: 16,
    color: fgMuted,
    margin: '0 0 0.5rem',
    lineHeight: 1.6,
  },
  spaceBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.35rem',
    padding: '0.3rem 0.8rem',
    borderRadius: 999,
    background: 'rgba(76,175,80,0.15)',
    border: '1px solid rgba(76,175,80,0.35)',
    color: '#66BB6A',
    fontSize: 13,
    fontWeight: 700,
    margin: '1rem 0 1.25rem',
  },
  spaceActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.7rem',
    marginTop: '0.5rem',
  },
  spaceBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    minHeight: 44,
    padding: '0.6rem 1rem',
    borderRadius: 12,
    border: 'none',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  spaceBtnPrimary: {
    background: 'linear-gradient(135deg, #6748FD, #947FFF)',
    color: '#FFFFFF',
  },
  spaceBtnGhost: {
    background: '#2C2C2E',
    color: fg,
    border: '1px solid #3A3A3C',
  },
};
